"""Python bindings for webspec-index.

Query WHATWG, W3C, TC39, and IETF web specifications: sections, cross-references,
WebIDL definitions, reference graphs, full-text search, WHATWG PR previews, and
source-file step-comment analysis.

All functions are synchronous; spec data is fetched and cached locally on first
use, exactly as the ``webspec-index`` CLI does.
"""

from ._webspec_index import (
    __version__,
    WebspecError,
    # result types
    QueryResult,
    Navigation,
    NavEntry,
    RefEntry,
    ExistsResult,
    AnchorsResult,
    AnchorEntry,
    SearchResult,
    SearchEntry,
    ListEntry,
    SpecUrlEntry,
    RefsResult,
    RefsMatch,
    IdlResult,
    IdlEntry,
    GraphResult,
    GraphRoot,
    GraphNode,
    GraphEdge,
    PrDiffResult,
    PrDiffSummary,
    PrDiffEntry,
    UpdateEntry,
    FileAnalysis,
    ScopeAnalysis,
    StepValidation,
    CoverageSummary,
    # functions
    query,
    exists,
    search,
    anchors,
    list_headings,
    refs,
    graph,
    idl,
    pr_diff,
    update,
    clear_pr,
    clear_db,
    specs,
    parse_anchor,
    analyze,
)

__all__ = [
    "__version__",
    "WebspecError",
    "QueryResult",
    "Navigation",
    "NavEntry",
    "RefEntry",
    "ExistsResult",
    "AnchorsResult",
    "AnchorEntry",
    "SearchResult",
    "SearchEntry",
    "ListEntry",
    "SpecUrlEntry",
    "RefsResult",
    "RefsMatch",
    "IdlResult",
    "IdlEntry",
    "GraphResult",
    "GraphRoot",
    "GraphNode",
    "GraphEdge",
    "PrDiffResult",
    "PrDiffSummary",
    "PrDiffEntry",
    "UpdateEntry",
    "FileAnalysis",
    "ScopeAnalysis",
    "StepValidation",
    "CoverageSummary",
    "query",
    "exists",
    "search",
    "anchors",
    "list_headings",
    "refs",
    "graph",
    "idl",
    "pr_diff",
    "update",
    "clear_pr",
    "clear_db",
    "specs",
    "parse_anchor",
    "analyze",
]
